{{- if .Values.PrometheusOperator -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    application: {{ template "fullname" . }}
  name: {{ template "fullname" . }}-file-env
data:
  template.yml: |
{{- include "template.tpl" . | indent 4 }}
{{- end -}}