apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
    application: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
automountServiceAccountToken: true