apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    application: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.general.containerPort }}
      protocol: TCP
      name: http
  selector:
    application: {{ template "fullname" . }}
    release: {{ .Release.Name }}
